### ISSUE TITLE
 ./resign.sh: No such file or directory

### ISSUE THREAD

**Issue by xpucuto** [dabear/iphoneipa-resign#1]
as-MacBook-Pro:~ Xpucu$ sudo pip install iResign
The directory '/Users/Xpucu/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Xpucu/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: iResign in /Library/Python/2.7/site-packages
as-MacBook-Pro:~ Xpucu$ ./resign.sh $HOME/Downloads/iosxdripreader-7.ipa $HOME/Downloads/iosxdripreader.mobileprovision
-bash: ./resign.sh: No such file or directory
This is where I got stuck . I am the main user and I don't know why this error is showing. Can you help me out  ?

**Comment by dabear** [comment]
You probably have to change directory into the directory where you downloaded the app.
```
cd $HOME/Downloads/iphoneipa-resign
```
(note that this may or may not be the directory in which you downloaded the file)

Then do an `ls` in the command line to see if resign.sh is listed

**Comment by xpucuto** [comment]
Sorry if I am talking nonsense but I haven't downloaded the resign app , only the ipa file from iosxdripreader. 
When I try the command above I get an error this directory doesn't exist  .

**Comment by dabear** [comment]
If you are going to run the resign app you need to download it first :)


25. jul. 2017 4.15 p.m. skrev "Hristina Dimova" <notifications@github.com>:

**Comment by dabear** [comment]
Download it then unzip it:
https://www.evernote.com/shard/s294/sh/b73a38b5-a26f-490c-bf75-58821d3001d0/1ad26a80dd055421

**Comment by xpucuto** [comment]
I guess I have missed that , silly me. 
You should  add that you have to run the command in the downloaded directory for dummies like me :) 
Thank you , its working now
